spring.application.name=CollabDesk

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/collabdesk}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.paths-to-match=/api/**,/csrf
springdoc.packages-to-scan=collabdesk

spring.cache.type=none
spring.data.redis.repositories.enabled=false
